# Generated by Django 3.2.8 on 2021-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('cod_item_venda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unit_venda', models.FloatField()),
            ],
            options={
                'db_table': 'itens_venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('cod_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField()),
                ('valor_total_venda', models.FloatField()),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
    ]
