# Generated by Django 3.2.8 on 2021-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('descr_produto', models.CharField(max_length=255)),
                ('valor_unit', models.FloatField()),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
    ]
